version: 2

defaults: &defaults
  docker:
  - image: groupbyinc/circleci-java

main_branch_only: &main_branch_only
  filters:
    branches:
      only:
        - develop

# common tasks
dependency_cache_key: &dependency_cache_key
  run:
    name: Generate Dependency Cache Key
    command: /scripts/checksum.sh /tmp/checksum

cache_key: &cache_key
  key: v1-dependencies-{{checksum "/tmp/checksum"}}

setup_builder: &setup_builder
  run:
    name: Initialize Build Agent
    command: /scripts/setup.sh

process_test_metadata: &process_test_metadata
  run:
    name: Process Test Metadata
    command: /scripts/process-test-results.sh
    when: always

store_test_results: &store_test_results
  store_test_results:
    path: ~/junit

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - *dependency_cache_key
    - restore_cache: *cache_key
    - *setup_builder
    - run: mvn -B -Pall,coverage
    - *process_test_metadata
    - *store_test_results
    - run: mvn -B dependency:go-offline
    - save_cache:
        <<: *cache_key
        paths:
        - ~/.m2
  release:
    <<: *defaults
    steps:
    - checkout
    - *dependency_cache_key
    - restore_cache: *cache_key
    - *setup_builder
    - run: mvn -B versions:update-parent -T10
    - run: git commit -am "updated parent version" || true
    - run: mvn -B release:prepare release:perform

workflows:
  version: 2
  build-and-push:
    jobs:
    - build:
        context: org-global
    - hold:
        <<: *main_branch_only
        type: approval
        requires:
        - build
    - release:
        <<: *main_branch_only
        context: org-global
        requires:
        - hold
